services:
  - type: web
    name: geospacial-crime-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ENV
        value: PRODUCTION
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        sync: false
      - key: COLLECTION_NAME
        sync: false
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - requirements.txt
        - main.py
    healthCheckPath: /health
    autoDeploy: true
